# Generated by Django 3.1.4 on 2021-03-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210302_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.BooleanField(null=True),
        ),
    ]
